# hotel_pairs_schema.py
from pyspark.sql.types import *

hotel_pairs_schema = StructType([
    StructField("id_i", StringType(), False),
    StructField("id_j", StringType(), False),
    StructField("providerHotelId_i", StringType(), False),
    StructField("providerHotelId_j", StringType(), False),
    StructField("name_i", StringType(), False),
    StructField("name_j", StringType(), False),
    StructField("uid_i", StringType(), False),
    StructField("uid_j", StringType(), False),
    StructField("normalized_name_i", StringType(), False),
    StructField("normalized_name_j", StringType(), False),
    StructField("combined_address_i", StringType(), False),
    StructField("combined_address_j", StringType(), False),
    # StructField("geoCode_lat_i", DoubleType(), True),
    # StructField("geoCode_long_i", DoubleType(), True),
    # StructField("geoCode_lat_j", DoubleType(), True),
    # StructField("geoCode_long_j", DoubleType(), True),
    StructField("geo_distance_km", DoubleType(), False),
    StructField("name_score_jaccard", FloatType(), False),
    StructField("normalized_name_score_jaccard", FloatType(), False),
    StructField("name_score_lcs", FloatType(), False),
    StructField("normalized_name_score_lcs", FloatType(), False),
    StructField("name_score_levenshtein", FloatType(), False),
    StructField("normalized_name_score_levenshtein", FloatType(), False),
    StructField("name_score_sbert", FloatType(), False),
    StructField("normalized_name_score_sbert", FloatType(), False),
    StructField("average_name_score", FloatType(), False),
    StructField("average_normalized_name_score", FloatType(), False),
    StructField("star_ratings_score", FloatType(), False),
    StructField("address_line1_score", FloatType(), False),
    StructField("postal_code_match", FloatType(), False),
    StructField("country_match", FloatType(), False),
    StructField("address_sbert_score", FloatType(), False),
    StructField("phone_match_score", FloatType(), False),
    StructField("email_match_score", FloatType(), False),
    StructField("fax_match_score", FloatType(), False),
    StructField("property_type_score", FloatType(), False),
    StructField("name_unit_score", FloatType(), False),
    StructField("address_unit_score", FloatType(), False),
    StructField("supplier_score", IntegerType(), False),
    StructField("providerName_i", StringType(), False),
    StructField("providerName_j", StringType(), False),
    StructField("type_i", StringType(), True),
    StructField("type_j", StringType(), True),
    StructField("name_score_containment", FloatType(), False),
    StructField("normalized_name_score_containment", FloatType(), False),
    StructField("name_residual_score", FloatType(), False),
    StructField("average_name_score", FloatType(), False),
    StructField("average_normalized_name_score", FloatType(), False),
    StructField("pair_key_left", StringType(), False),
    StructField("pair_key_right", StringType(), False),
    StructField("overall_pair_score", FloatType(), False)
])
