# hotel_pairs_schema.py
from pyspark.sql.types import *

hotel_pairs_schema = StructType([
    StructField("id_i", StringType(), False),
    StructField("id_j", StringType(), False),
    StructField("providerHotelId_i", StringType(), False),
    StructField("providerHotelId_j", StringType(), False),
    StructField("name_i", StringType(), False),
    StructField("name_j", StringType(), False),
    StructField("normalized_name_i", StringType(), False),
    StructField("normalized_name_j", StringType(), False),
    # StructField("geoCode_lat_i", DoubleType(), True),
    # StructField("geoCode_long_i", DoubleType(), True),
    # StructField("geoCode_lat_j", DoubleType(), True),
    # StructField("geoCode_long_j", DoubleType(), True),
    StructField("geo_distance_km", DoubleType(), False),
    StructField("name_score_jaccard_lcs", FloatType(), False),
    StructField("normalized_name_score_jaccard_lcs", FloatType(), False),
    StructField("name_score_sbert", FloatType(), False),
    StructField("normalized_name_score_sbert", FloatType(), False),
    StructField("star_ratings_score", FloatType(), False),
    StructField("address_line1_score", FloatType(), False),
    StructField("postal_code_match", FloatType(), False),
    StructField("country_match", FloatType(), False),
    StructField("address_sbert_score", FloatType(), False),
    StructField("phone_match_score", FloatType(), False),
    StructField("email_match_score", FloatType(), False),
    StructField("fax_match_score", FloatType(), False),
])
